# Generated by Django 4.0.4 on 2022-07-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olx_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукт'},
        ),
    ]
